language: java
jdk:
 - openjdk8
services:
 - mongodb
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: oliot-tsd
install:
 - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
 - mvn test jacoco:report
after_success:
 - mvn coveralls:report