version: "3.1"

services:
  database:
    build:
       context: ./db
    image: tsd_db
    volumes:
        - "./db/data:/data/db"
    ports:
      - "27017:27017"
    networks:
      - back-tier

networks:
  back-tier:
